# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Patients_DB.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Patients_DB(object):
    def setupUi(self, Patients_DB):
        print('setupUI_Ui_Patient_DB')
        Patients_DB.setObjectName("Patients_DB")
        Patients_DB.resize(530, 299)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Patients_DB)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 371, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.Name_HL = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.Name_HL.setContentsMargins(0, 0, 0, 0)
        self.Name_HL.setObjectName("Name_HL")
        self.First_Name_VL = QtWidgets.QVBoxLayout()
        self.First_Name_VL.setObjectName("First_Name_VL")
        self.FirstName = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.FirstName.setObjectName("FirstName")
        self.First_Name_VL.addWidget(self.FirstName)
        self.FirstNameBox = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.FirstNameBox.setObjectName("FirstNameBox")
        self.First_Name_VL.addWidget(self.FirstNameBox)
        self.Name_HL.addLayout(self.First_Name_VL)
        self.Last_Name_VL = QtWidgets.QVBoxLayout()
        self.Last_Name_VL.setObjectName("Last_Name_VL")
        self.LastName = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.LastName.setObjectName("LastName")
        self.Last_Name_VL.addWidget(self.LastName)
        self.LastNameBox = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.LastNameBox.setObjectName("LastNameBox")
        self.Last_Name_VL.addWidget(self.LastNameBox)
        self.Name_HL.addLayout(self.Last_Name_VL)
        self.Search = QtWidgets.QPushButton(Patients_DB)
        self.Search.setGeometry(QtCore.QRect(400, 20, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Search.setFont(font)
        self.Search.setObjectName("Search")
        self.Add = QtWidgets.QPushButton(Patients_DB)
        self.Add.setGeometry(QtCore.QRect(350, 240, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Add.setFont(font)
        self.Add.setObjectName("Add")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Patients_DB)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(350, 90, 160, 89))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.View_AMI_Del_VL = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.View_AMI_Del_VL.setContentsMargins(0, 0, 0, 0)
        self.View_AMI_Del_VL.setObjectName("View_AMI_Del_VL")
        self.View = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.View.setFont(font)
        self.View.setObjectName("View")
        self.View_AMI_Del_VL.addWidget(self.View)
        self.Add_medical_image = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Add_medical_image.setFont(font)
        self.Add_medical_image.setObjectName("Add_medical_image")
        self.View_AMI_Del_VL.addWidget(self.Add_medical_image)
        self.Delete = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Delete.setFont(font)
        self.Delete.setObjectName("Delete")
        self.View_AMI_Del_VL.addWidget(self.Delete)
        self.scrollArea = QtWidgets.QScrollArea(Patients_DB)
        self.scrollArea.setGeometry(QtCore.QRect(10, 90, 321, 181))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 319, 179))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(10, 10, 271, 81))
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("background-color: rgb(138, 138, 138);")
        self.widget.setObjectName("widget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 251, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.Patient_info_GL = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.Patient_info_GL.setContentsMargins(0, 0, 0, 0)
        self.Patient_info_GL.setObjectName("Patient_info_GL")
        self.Full_Name = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Full_Name.setObjectName("Full_Name")
        self.Patient_info_GL.addWidget(self.Full_Name, 0, 0, 1, 1)
        self.Father = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Father.setObjectName("Father")
        self.Patient_info_GL.addWidget(self.Father, 1, 0, 1, 1)
        self.Mother = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Mother.setObjectName("Mother")
        self.Patient_info_GL.addWidget(self.Mother, 2, 0, 1, 1)
        self.Mother_value = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Mother_value.setObjectName("Mother_value")
        self.Patient_info_GL.addWidget(self.Mother_value, 2, 1, 1, 1)
        self.Father_value = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Father_value.setObjectName("Father_value")
        self.Patient_info_GL.addWidget(self.Father_value, 1, 1, 1, 1)
        self.Last_Visit = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Last_Visit.setObjectName("Last_Visit")
        self.Patient_info_GL.addWidget(self.Last_Visit, 3, 0, 1, 1)
        self.Last_Visit_value = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Last_Visit_value.setObjectName("Last_Visit_value")
        self.Patient_info_GL.addWidget(self.Last_Visit_value, 3, 1, 1, 1)
        self.Full_Name_value = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Full_Name_value.setObjectName("Full_Name_value")
        self.Patient_info_GL.addWidget(self.Full_Name_value, 0, 1, 1, 1)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.scrollAreaWidgetContents)
        self.verticalScrollBar.setGeometry(QtCore.QRect(300, 0, 20, 181))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Patients_DB)
        QtCore.QMetaObject.connectSlotsByName(Patients_DB)

    def retranslateUi(self, Patients_DB):
        print('retranslateUi_Patient_DB')
        _translate = QtCore.QCoreApplication.translate
        Patients_DB.setWindowTitle(_translate("Patients_DB", "Patients DB"))
        self.FirstName.setText(_translate("Patients_DB", "First Name"))
        self.LastName.setText(_translate("Patients_DB", "Last Name"))
        self.Search.setText(_translate("Patients_DB", "Search"))
        self.Add.setText(_translate("Patients_DB", "Add"))
        self.View.setText(_translate("Patients_DB", "View"))
        self.Add_medical_image.setText(_translate("Patients_DB", "Add Medical Image"))
        self.Delete.setText(_translate("Patients_DB", "Delete"))
        self.Full_Name.setText(_translate("Patients_DB", "Full Name"))
        self.Father.setText(_translate("Patients_DB", "Father"))
        self.Mother.setText(_translate("Patients_DB", "Mother"))
        self.Mother_value.setText(_translate("Patients_DB", "Amira"))
        self.Father_value.setText(_translate("Patients_DB", "Samer"))
        self.Last_Visit.setText(_translate("Patients_DB", "Last Visit"))
        self.Last_Visit_value.setText(_translate("Patients_DB", "12 - 3 -2015"))
        self.Full_Name_value.setText(_translate("Patients_DB", "Ahmad Bassem"))
        print('retranslateUi_Patient_DB_END')



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Patients_DB = QtWidgets.QWidget()
    ui = Ui_Patients_DB()
    ui.setupUi(Patients_DB)
    Patients_DB.show()
    sys.exit(app.exec_())

