# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './PulseRecording1.ui'
#
# Created: Sun Jan 13 12:45:08 2019
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PulseRecording1(object):
    def setupUi(self, PulseRecording1):
        PulseRecording1.setObjectName("PulseRecording1")
        PulseRecording1.resize(400, 311)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(PulseRecording1)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 371, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.Name_HL = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.Name_HL.setContentsMargins(0, 0, 0, 0)
        self.Name_HL.setObjectName("Name_HL")
        self.First_Name_VL = QtWidgets.QVBoxLayout()
        self.First_Name_VL.setObjectName("First_Name_VL")
        self.FirstName = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.FirstName.setObjectName("FirstName")
        self.First_Name_VL.addWidget(self.FirstName)
        self.FirstNameBox = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.FirstNameBox.setObjectName("FirstNameBox")
        self.First_Name_VL.addWidget(self.FirstNameBox)
        self.Name_HL.addLayout(self.First_Name_VL)
        self.Last_Name_VL = QtWidgets.QVBoxLayout()
        self.Last_Name_VL.setObjectName("Last_Name_VL")
        self.LastName = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.LastName.setObjectName("LastName")
        self.Last_Name_VL.addWidget(self.LastName)
        self.LastNameBox = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.LastNameBox.setObjectName("LastNameBox")
        self.Last_Name_VL.addWidget(self.LastNameBox)
        self.Name_HL.addLayout(self.Last_Name_VL)
        self.scrollArea = QtWidgets.QScrollArea(PulseRecording1)
        self.scrollArea.setGeometry(QtCore.QRect(10, 80, 321, 181))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 319, 179))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.Patient = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.Patient.setGeometry(QtCore.QRect(10, 10, 271, 81))
        self.Patient.setAutoFillBackground(False)
        self.Patient.setStyleSheet("background-color: rgb(138, 138, 138);")
        self.Patient.setObjectName("Patient")
        self.gridLayoutWidget = QtWidgets.QWidget(self.Patient)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 251, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.Patient_info_GL = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.Patient_info_GL.setContentsMargins(0, 0, 0, 0)
        self.Patient_info_GL.setObjectName("Patient_info_GL")
        self.Full_Name = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Full_Name.setObjectName("Full_Name")
        self.Patient_info_GL.addWidget(self.Full_Name, 0, 0, 1, 1)
        self.Father = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Father.setObjectName("Father")
        self.Patient_info_GL.addWidget(self.Father, 1, 0, 1, 1)
        self.Mother = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Mother.setObjectName("Mother")
        self.Patient_info_GL.addWidget(self.Mother, 2, 0, 1, 1)
        self.Mother_value = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Mother_value.setObjectName("Mother_value")
        self.Patient_info_GL.addWidget(self.Mother_value, 2, 1, 1, 1)
        self.Father_value = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Father_value.setObjectName("Father_value")
        self.Patient_info_GL.addWidget(self.Father_value, 1, 1, 1, 1)
        self.Last_Visit = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Last_Visit.setObjectName("Last_Visit")
        self.Patient_info_GL.addWidget(self.Last_Visit, 3, 0, 1, 1)
        self.Last_Visit_value = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Last_Visit_value.setObjectName("Last_Visit_value")
        self.Patient_info_GL.addWidget(self.Last_Visit_value, 3, 1, 1, 1)
        self.Full_Name_value = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Full_Name_value.setObjectName("Full_Name_value")
        self.Patient_info_GL.addWidget(self.Full_Name_value, 0, 1, 1, 1)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.scrollAreaWidgetContents)
        self.verticalScrollBar.setGeometry(QtCore.QRect(300, 0, 20, 181))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.Next = QtWidgets.QPushButton(PulseRecording1)
        self.Next.setGeometry(QtCore.QRect(310, 280, 80, 23))
        self.Next.setObjectName("Next")
        self.Back = QtWidgets.QPushButton(PulseRecording1)
        self.Back.setGeometry(QtCore.QRect(220, 280, 80, 23))
        self.Back.setObjectName("Back")

        self.retranslateUi(PulseRecording1)
        QtCore.QMetaObject.connectSlotsByName(PulseRecording1)

    def retranslateUi(self, PulseRecording1):
        _translate = QtCore.QCoreApplication.translate
        PulseRecording1.setWindowTitle(_translate("PulseRecording1", "Form"))
        self.FirstName.setText(_translate("PulseRecording1", "First Name"))
        self.LastName.setText(_translate("PulseRecording1", "Last Name"))
        self.Full_Name.setText(_translate("PulseRecording1", "Full Name"))
        self.Father.setText(_translate("PulseRecording1", "Father"))
        self.Mother.setText(_translate("PulseRecording1", "Mother"))
        self.Mother_value.setText(_translate("PulseRecording1", "Amira"))
        self.Father_value.setText(_translate("PulseRecording1", "Samer"))
        self.Last_Visit.setText(_translate("PulseRecording1", "Last Visit"))
        self.Last_Visit_value.setText(_translate("PulseRecording1", "12 - 3 -2015"))
        self.Full_Name_value.setText(_translate("PulseRecording1", "Ahmad Bassem"))
        self.Next.setText(_translate("PulseRecording1", "Next"))
        self.Back.setText(_translate("PulseRecording1", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PulseRecording1 = QtWidgets.QWidget()
    ui = Ui_PulseRecording1()
    ui.setupUi(PulseRecording1)
    PulseRecording1.show()
    sys.exit(app.exec_())

