# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './PulseRecording2.ui'
#
# Created: Sun Jan 13 12:45:09 2019
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PulseRecording2(object):
    def setupUi(self, PulseRecording2):
        PulseRecording2.setObjectName("PulseRecording2")
        PulseRecording2.resize(657, 390)
        self.Patient = QtWidgets.QWidget(PulseRecording2)
        self.Patient.setGeometry(QtCore.QRect(10, 40, 271, 81))
        self.Patient.setAutoFillBackground(False)
        self.Patient.setStyleSheet("background-color: rgb(138, 138, 138);")
        self.Patient.setObjectName("Patient")
        self.gridLayoutWidget = QtWidgets.QWidget(self.Patient)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 251, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.Patient_info_GL = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.Patient_info_GL.setContentsMargins(0, 0, 0, 0)
        self.Patient_info_GL.setObjectName("Patient_info_GL")
        self.Full_Name = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Full_Name.setObjectName("Full_Name")
        self.Patient_info_GL.addWidget(self.Full_Name, 0, 0, 1, 1)
        self.Father = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Father.setObjectName("Father")
        self.Patient_info_GL.addWidget(self.Father, 1, 0, 1, 1)
        self.Mother = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Mother.setObjectName("Mother")
        self.Patient_info_GL.addWidget(self.Mother, 2, 0, 1, 1)
        self.Mother_value = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Mother_value.setObjectName("Mother_value")
        self.Patient_info_GL.addWidget(self.Mother_value, 2, 1, 1, 1)
        self.Father_value = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Father_value.setObjectName("Father_value")
        self.Patient_info_GL.addWidget(self.Father_value, 1, 1, 1, 1)
        self.Last_Visit = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Last_Visit.setObjectName("Last_Visit")
        self.Patient_info_GL.addWidget(self.Last_Visit, 3, 0, 1, 1)
        self.Last_Visit_value = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Last_Visit_value.setObjectName("Last_Visit_value")
        self.Patient_info_GL.addWidget(self.Last_Visit_value, 3, 1, 1, 1)
        self.Full_Name_value = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Full_Name_value.setObjectName("Full_Name_value")
        self.Patient_info_GL.addWidget(self.Full_Name_value, 0, 1, 1, 1)
        self.Patient_info_3 = QtWidgets.QLabel(self.Patient)
        self.Patient_info_3.setGeometry(QtCore.QRect(270, 60, 180, 18))
        self.Patient_info_3.setObjectName("Patient_info_3")
        self.Patient_info = QtWidgets.QLabel(PulseRecording2)
        self.Patient_info.setGeometry(QtCore.QRect(10, 10, 180, 18))
        self.Patient_info.setObjectName("Patient_info")
        self.horizontalLayoutWidget = QtWidgets.QWidget(PulseRecording2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(470, 350, 181, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Main = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Main.setObjectName("Main")
        self.horizontalLayout.addWidget(self.Main)
        self.Back = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Back.setObjectName("Back")
        self.horizontalLayout.addWidget(self.Back)
        self.graphicsView_plot = QtWidgets.QGraphicsView(PulseRecording2)
        self.graphicsView_plot.setGeometry(QtCore.QRect(320, 10, 321, 261))
        self.graphicsView_plot.setObjectName("graphicsView_plot")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(PulseRecording2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 270, 160, 25))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.Duration_hl = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.Duration_hl.setContentsMargins(0, 0, 0, 0)
        self.Duration_hl.setObjectName("Duration_hl")
        self.Duration = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.Duration.setObjectName("Duration")
        self.Duration_hl.addWidget(self.Duration)
        self.DurationBox = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.DurationBox.setObjectName("DurationBox")
        self.Duration_hl.addWidget(self.DurationBox)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(PulseRecording2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(320, 270, 151, 21))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.HeartRate_hl = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.HeartRate_hl.setContentsMargins(0, 0, 0, 0)
        self.HeartRate_hl.setObjectName("HeartRate_hl")
        self.HeartRate = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.HeartRate.setObjectName("HeartRate")
        self.HeartRate_hl.addWidget(self.HeartRate)
        self.HeartRate_value = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setBold(True)
        font.setWeight(75)
        self.HeartRate_value.setFont(font)
        self.HeartRate_value.setObjectName("HeartRate_value")
        self.HeartRate_hl.addWidget(self.HeartRate_value)
        self.Start = QtWidgets.QPushButton(PulseRecording2)
        self.Start.setGeometry(QtCore.QRect(10, 310, 80, 23))
        self.Start.setObjectName("Start")
        self.Save = QtWidgets.QPushButton(PulseRecording2)
        self.Save.setGeometry(QtCore.QRect(10, 340, 80, 23))
        self.Save.setObjectName("Save")
        self.Stop = QtWidgets.QPushButton(PulseRecording2)
        self.Stop.setGeometry(QtCore.QRect(110, 310, 80, 23))
        self.Stop.setObjectName("Stop")
        self.MicroBit = QtWidgets.QWidget(PulseRecording2)
        self.MicroBit.setGeometry(QtCore.QRect(10, 160, 191, 51))
        self.MicroBit.setAutoFillBackground(False)
        self.MicroBit.setStyleSheet("background-color: rgb(32, 122, 200);\n"
"border-color: rgb(27, 31, 66);")
        self.MicroBit.setObjectName("MicroBit")
        self.Patient_info_4 = QtWidgets.QLabel(self.MicroBit)
        self.Patient_info_4.setGeometry(QtCore.QRect(270, 60, 180, 18))
        self.Patient_info_4.setObjectName("Patient_info_4")
        self.MicroBitPort = QtWidgets.QLabel(self.MicroBit)
        self.MicroBitPort.setGeometry(QtCore.QRect(0, 10, 81, 19))
        self.MicroBitPort.setObjectName("MicroBitPort")
        self.MicroBitPortBox = QtWidgets.QLineEdit(self.MicroBit)
        self.MicroBitPortBox.setGeometry(QtCore.QRect(90, 10, 99, 19))
        self.MicroBitPortBox.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.MicroBitPortBox.setObjectName("MicroBitPortBox")
        self.MB_connection = QtWidgets.QLabel(self.MicroBit)
        self.MB_connection.setGeometry(QtCore.QRect(0, 30, 191, 21))
        self.MB_connection.setObjectName("MB_connection")
        self.MicroBit_settings = QtWidgets.QLabel(PulseRecording2)
        self.MicroBit_settings.setGeometry(QtCore.QRect(10, 140, 180, 18))
        self.MicroBit_settings.setObjectName("MicroBit_settings")

        self.retranslateUi(PulseRecording2)
        QtCore.QMetaObject.connectSlotsByName(PulseRecording2)

    def retranslateUi(self, PulseRecording2):
        _translate = QtCore.QCoreApplication.translate
        PulseRecording2.setWindowTitle(_translate("PulseRecording2", "Form"))
        self.Full_Name.setText(_translate("PulseRecording2", "Full Name"))
        self.Father.setText(_translate("PulseRecording2", "Father"))
        self.Mother.setText(_translate("PulseRecording2", "Mother"))
        self.Mother_value.setText(_translate("PulseRecording2", "Amira"))
        self.Father_value.setText(_translate("PulseRecording2", "Samer"))
        self.Last_Visit.setText(_translate("PulseRecording2", "Last Visit"))
        self.Last_Visit_value.setText(_translate("PulseRecording2", "12 - 3 -2015"))
        self.Full_Name_value.setText(_translate("PulseRecording2", "Ahmad Bassem"))
        self.Patient_info_3.setText(_translate("PulseRecording2", "Patient info:"))
        self.Patient_info.setText(_translate("PulseRecording2", "Patient info:"))
        self.Main.setText(_translate("PulseRecording2", "Main"))
        self.Back.setText(_translate("PulseRecording2", "Back"))
        self.Duration.setText(_translate("PulseRecording2", "Duration"))
        self.HeartRate.setText(_translate("PulseRecording2", "Heart Rate"))
        self.HeartRate_value.setText(_translate("PulseRecording2", "0.0"))
        self.Start.setText(_translate("PulseRecording2", "Start"))
        self.Save.setText(_translate("PulseRecording2", "Save"))
        self.Stop.setText(_translate("PulseRecording2", "Stop"))
        self.Patient_info_4.setText(_translate("PulseRecording2", "Patient info:"))
        self.MicroBitPort.setText(_translate("PulseRecording2", "MicroBit Port"))
        self.MB_connection.setText(_translate("PulseRecording2", "MicroBit is Connected"))
        self.MicroBit_settings.setText(_translate("PulseRecording2", "MicroBit Settings:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PulseRecording2 = QtWidgets.QWidget()
    ui = Ui_PulseRecording2()
    ui.setupUi(PulseRecording2)
    PulseRecording2.show()
    sys.exit(app.exec_())

